# Auto generated by ./aptly-update-cld.sh.
GF_ADD_SOURCE_LIST live "deb http://repo.aptly.info/ squeeze main"
GF_ADD_SOURCE_LIST live "deb http://www.deb-multimedia.org stretch main non-free"
GF_ADD_SOURCE_LIST live "deb http://http.debian.net/debian stretch-backports main contrib non-free"
GF_ADD_SOURCE_LIST live "deb http://security.debian.org/ stretch/updates main contrib non-free"
GF_ADD_SOURCE_LIST live "deb http://ftp.debian.org/debian stretch main contrib non-free"
GF_ADD_SOURCE_LIST live "deb http://ftp.debian.org/debian/ stretch-updates main contrib non-free"

