# Auto generated by ./aptly-update-cld.sh.
GF_ADD_SOURCE_LIST live "deb http://ftp.debian.org/debian buster main contrib non-free"
GF_ADD_SOURCE_LIST live "deb http://ftp.debian.org/debian/ buster-updates main contrib non-free"

# Add security source url but don't upgrade security package. It might brake or remove packages.
GF_ADD_SOURCE_LIST live "deb http://security.debian.org/ buster/updates main contrib non-free"

GF_ADD_SOURCE_LIST live "deb http://http.debian.net/debian buster-backports main contrib non-free"

