# Auto generated by ./aptly-update-cld.sh.
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_buster-security-contrib buster-updates contrib"
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_buster-security-main buster-updates main"
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_buster-security-non-free buster-updates non-free"
