# Auto generated by ./aptly-update-cld.sh.
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_stretch-security-contrib stretch-updates contrib"
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_stretch-security-main stretch-updates main"
GF_ADD_SOURCE_LIST tmp "deb http://localhost/aptly-repo/master_stretch-security-non-free stretch-updates non-free"
