#!/bin/bash
set -e
# Description: Download all files listed in to-dl-*.list.
# to-dl-<DIRECTORY_NAME>.list
# https://github.com/rg3/youtube-dl/blob/master/README.md#output-template

while IFS='' read -r FILENAME || [[ -n "${FILENAME}" ]]; do
  
  if [ -e "${FILENAME}" ]; then
  
    DIR_NAME=$(echo "${FILENAME}" | sed 's/to-dl-//' | sed 's/\.list$//')
    mkdir -p "${DIR_NAME}"
    DIR_NAME=$(readlink -ev "${DIR_NAME}")
    
    youtube-dl -i -o "${DIR_NAME}/%(title)s-%(id)s.%(ext)s" $(cat "${FILENAME}"| grep -v '^#' | awk NF)
    
  else
  
    echo "Warning: Skip ${FILENAME}: no such file!"
    
  fi
 
done < <( ls -1 $@ )
