#!/bin/bash
set -e
# Description: Download all files listed in to-dl-*.list.
# to-dl-<DIRECTORY_NAME>.list

while IFS='' read -r FILENAME || [[ -n "${FILENAME}" ]]; do
  
  DIR_NAME=$(echo "${FILENAME}" | sed 's/to-dl-//' | sed 's/\.list$//')
  mkdir -p "${DIR_NAME}"
  
  youtube-dl -o "${DIR_NAME}/%(title)s-%(id)s.%(ext)s" $(cat "${FILENAME}"| grep -v '^#' | awk NF)
 
done < <( ls -1 to-dl-*.list )
